version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: Zones
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dost
    ports:
      - "5432:5432"
